### ISSUE TITLE
Fable TLC's vertex data

### ISSUE THREAD

**Issue by jamen** [Keshire/Fable-3-GDB-Tool#1]
Hi. I wasn't sure how to reach you, so I'm posting this issue.

I'm working on [parsing all of Fable's data](https://github.com/jamen/open_albion/tree/master/fable_data) to make a viewer. fabletlcmod.com has been a good resource, but its missing some information, and all the context from reverse engineering. One thing I want to ask about is vertex data, because [the mesh description stops there](http://fabletlcmod.com/wiki/doku.php?id=file_formats:bbm#sub-mesh), and it becomes rather complex because vertices can have different size and attributes. The unknowns in the sub-mesh and the vertex size seem involved in deciding what attributes to use at least.

Let me know if there's a better way to reach you like email.

**Comment by Keshire** [comment]
It's been so many years. I don't really remember anymore. But somewhere in that submesh block determines what kind of verts it uses.

________________________________
From: Jamen Marz ***@***.***>
Sent: Monday, May 17, 2021 12:27 AM
To: Keshire/Fable-3-GDB-Tool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Keshire/Fable-3-GDB-Tool] Fable TLC's vertex data (#1)


Hi. I wasn't sure how to reach you, so I'm posting this issue.

I'm working on [parsing all of Fable's data]https://github.com/jamen/open_albion/tree/master/fable_data)) to make a viewer. fabletlcmod.com has been a good reference, but its missing some information, and all the reverse engineering context. One thing I want to ask about is vertex data, because the mesh description stops there<http://fabletlcmod.com/wiki/doku.php?id=file_formats:bbm#sub-mesh>, and it becomes rather complex because vertices can have different size and attributes. The unknowns in the sub-mesh and the vertex size seem involved in deciding what attributes to use at least.

Let me know if there's a better way to reach you like email.

**Comment by jamen** [comment]
Yeah, thats been tough to figure out. I learned that some meshes use triangle strips instead of lists last night at least.

Do you still have Chocolate Box, Fable Explorer, or ShadowNet's source code? That would be super helpful.

**Comment by Keshire** [comment]
I do not. It was originally a hosted SVN by Hunter on the forums. But when he dropped off the radar so did the SVN.

________________________________

**Comment by jamen** [comment]
Ah, that's a shame. Well, thank you for answering my questions. I'll let you know if anything happens.
